export const FETCH_LOGIN_USER_START = 'FETCH_LOGIN_USER_START';
export const FETCH_LOGIN_USER_SUCCESS = 'FETCH_LOGIN_USER_SUCCESS';
export const FETCH_LOGIN_USER_FAIL = 'FETCH_LOGIN_USER_FAIL';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const SENDING_PROFILE_DATA_START = 'SENDING_PROFILE_DATA_START';
export const SENDING_PROFILE_DATA_SUCCESS = 'SENDING_PROFILE_DATA_SUCCESS';
export const SENDING_PROFILE_DATA_FAIL = 'SENDING_PROFILE_DATA_FAIL';
