export const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER';
export const FETCH_LOGIN_USER_START = 'FETCH_LOGIN_USER_START';
export const FETCH_LOGIN_USER_SUCCESS = 'FETCH_LOGIN_USER_SUCCESS';
export const FETCH_LOGIN_USER_FAIL = 'FETCH_LOGIN_USER_FAIL';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const SENDING_PROFILE_DATA = 'SENDING_PROFILE_DATA';
export const SENDING_PROFILE_DATA_START = 'SENDING_PROFILE_DATA_START';
export const SENDING_PROFILE_DATA_SUCCESS = 'SENDING_PROFILE_DATA_SUCCESS';
export const SENDING_PROFILE_DATA_FAIL = 'SENDING_PROFILE_DATA_FAIL';

export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const FETCH_ADDRESSES_START = 'FETCH_ADDRESSES_START';
export const FETCH_ADDRESSES_SUCCESS = 'FETCH_ADDRESSES_SUCCESS';
export const FETCH_ADDRESSES_FAIL = 'FETCH_ADDRESSES_FAIL';

export const FETCH_ROUTES = 'FETCH_ROUTES';
export const FETCH_ROUTES_START = 'FETCH_ROUTES_START';
export const FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS';
export const FETCH_ROUTES_FAIL = 'FETCH_ROUTES_FAIL';

export const CANCEL_REQUEST = 'CANCEL_REQUEST';

export const LOGOUT_USER = 'LOGOUT_USER';
